services:
  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./:/directus/extensions/imagga
    env_file: ".env.test"
  imagga:
    image: wiremock/wiremock:3.12.1
    ports:
      - 8080:8080
    volumes:
      - ./mocks:/home/wiremock
