services:
  directus:
    image: directus/directus:11.16.1@sha256:8543bb57029d6e4087fd6bd83944233b271b3858465aa8e43d888e618bbe0a69
    ports:
      - 8055:8055
    volumes:
      - ./:/directus/extensions/imagga
    env_file: ".env.test"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8055/server/health || exit 1"]
      start_period: 20s
  imagga:
    image: wiremock/wiremock:3.13.2@sha256:fd27e46090916e85326229e5102ee169ae729059f3374549615bd20a35fee1f2
    ports:
      - 8080:8080
    volumes:
      - ./mocks:/home/wiremock
