services:
  directus:
    image: directus/directus:11.4.1
    ports:
      - 8055:8055
    volumes:
      - ./:/directus/extensions/imagga
    env_file: ".env.test"
  imagga:
    image: wiremock/wiremock:3.11.0
    ports:
      - 8080:8080
    volumes:
      - ./mocks:/home/wiremock
