services:
  directus:
    image: directus/directus:11.2.2
    ports:
      - 8055:8055
    volumes:
      - ./:/directus/extensions/imagga
    env_file: ".env.test"
  imagga:
    image: mockserver/mockserver:5.15.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /mocks/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /mocks/imagga.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
    volumes:
      - ./mocks:/mocks
