services:
  directus:
    image: directus/directus:11.2.2
    ports:
      - 8055:8055
    volumes:
      - ./:/directus/extensions/imagga
    env_file: ".env.test"
  imagga:
    image: wiremock/wiremock:latest
    ports:
      - 8080:8080
    volumes:
      - ./mocks:/home/wiremock
