name: Prepare
description: Install dependencies and build

runs:
  using: "composite"
  steps:
    - name: Install pnpm package manager
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4

    - name: Setup Node.js environment
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
        scope: "@bicou"
        registry-url: "https://registry.npmjs.org/"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
