name: Prepare
description: Install dependencies and build

runs:
  using: "composite"
  steps:
    - name: Install pnpm package manager
      uses: pnpm/action-setup@71c92474e7e4f5bca283fb17ef80fba9cdb2b4b1 # v6

    - name: Setup Node.js environment
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
        scope: "@bicou"
        registry-url: "https://registry.npmjs.org/"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
