name: Prepare
description: Install dependencies and build

runs:
  using: "composite"
  steps:
    - name: Install pnpm package manager
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

    - name: Setup Node.js environment
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
        scope: "@bicou"
        registry-url: "https://registry.npmjs.org/"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
