name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Prepare and Build
        uses: ./.github/actions/prepare

      - name: Build
        run: pnpm build

      - name: Start docker services
        uses: hoverkraft-tech/compose-action@d2bee4f07e8ca410d6b196d00f90c12e7d48c33a # v2
        with:
          compose-file: docker-compose.test.yaml
          up-flags: '--wait'

      - name: Run tests
        run: pnpm test
